package Recursion;

import java.util.ArrayList;
import java.util.Scanner;

public class Recursion9 {

    // Q1. Given a string WAM to return all its subsequences in a arraylist.A string
    // is a subsequence of a given String that is generated by deleting some
    // charcter of a given string without changing its order.
    // if strign.length = n then subsequences = 2^n
    static ArrayList<String> getSSQ(String s) {
        /*
         * s=abc
         */
        ArrayList<String> ans = new ArrayList<>();
        // base case
        if (s.length() == 0) {
            ans.add("");
            return ans;
        }

        char curr = s.charAt(0); // a
        ArrayList<String> smallAns = getSSQ(s.substring(1));// ["bc","b","c",""]

        // ans = ["bc","b","c","" "abc","ab","ac","a"]
        for (String ss : smallAns) {
            ans.add(ss); // bc
            ans.add(curr + ss); // abc
        }
        return ans;
    }

    // Q2 : Given a string write a method to print all its subsequences. : its
    // better approach in terms of space.
    //

    static void printSSQ(String s, String currAns) { // s = "abc" ,currAns =""

        if (s.length() == 0) {
            System.out.println(currAns);
            return;
        }

        char curr = s.charAt(0);
        String remString = s.substring(1);

        // curr Char --> chooses to be a part of currAns.
        printSSQ(remString, currAns + curr);
        // curr Char --> chooses not to be a part of currAns.
        printSSQ(remString, currAns);
    }

    // Q3 : Given an array of integers,print sums of all subsets in it. Output sums
    // can be printed in any order.ex input ={2,4,5} output : {0,2,4,5,6,7,9,11}

    static void subSetsSum(int[] arr, int n, int idx, int sum) {

        if (idx >= n) {
            System.out.println(sum);
            return;
        }

        // curr idx + sum

        subSetsSum(arr, n, idx + 1, sum + arr[idx]); // include

        // curr ans

        subSetsSum(arr, n, idx + 1, sum); // exclude
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter a String");
        String s = sc.nextLine();
        // System.out.println(getSSQ(s));
        // printSSQ(s, "");

        int arr[] = { 2, 4, 5 };
        subSetsSum(arr, arr.length, 0, 0);

    }
}
